-- Création de la base de données
CREATE DATABASE budbud;

-- Connexion à la base
\c budbud;

-- Table des équipes
CREATE TABLE equipes (
    id SERIAL PRIMARY KEY,
    nom VARCHAR(100) NOT NULL,
    active BOOLEAN DEFAULT TRUE
);

-- Table des types de repêchage
CREATE TABLE types_repechage (
    id SERIAL PRIMARY KEY,
    nom VARCHAR(100) NOT NULL
);

-- Table des repêchages
CREATE TABLE repechages (
    id SERIAL PRIMARY KEY,
    annee INT NOT NULL,
    type_id INT REFERENCES types_repechage(id),
    equipe_id INT REFERENCES equipes(id),
    joueur VARCHAR(100) NOT NULL,
    rang INT NOT NULL,
    round INT NUll 
);

-- Table des échanges
CREATE TABLE echanges (
    id SERIAL PRIMARY KEY,
    date DATE NOT NULL,
    equipe_source_id INT REFERENCES equipes(id),
    equipe_destination_id INT REFERENCES equipes(id),
    details TEXT
);

-- Table des trophées
CREATE TABLE trophees (
    id SERIAL PRIMARY KEY,
    nom VARCHAR(100) NOT NULL
);

-- Table des gagnants de trophées
CREATE TABLE trophee_gagnants (
    id SERIAL PRIMARY KEY,
    trophee_id INT REFERENCES trophees(id),
    annee INT NOT NULL,
    equipe_id INT REFERENCES equipes(id),
    joueur VARCHAR(100)
);

-- Insérer les équipes si ce n'est pas déjà fait
INSERT INTO equipes (nom) VALUES
('Canadiens Français de la Rivière aux Graines'),
('Consanguins de Laterrière'),
('Chiennes de Granby'),
('Dream Team de Saint-Pie-X'),
('Vidanges de Rimouski'),
('Les Ptit-Pains Fourrés de Limoilou'),
('Enculés de Westmount'),
('Alex Lirette (TEMPORAIRE)');

-- Insérer les types de repêchage
INSERT INTO types_repechage (nom) VALUES
('Ballotage'),
('Draft annuel'),
('Draft d''expansion');

-- Insérer les échanges de la saison 2022-2023
INSERT INTO echanges (date, equipe_source_id, equipe_destination_id, details) VALUES
('2022-10-23',
 (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'),
 (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'),
 'CO reçoit: Nico Hischier, Sergei Bobrovsky | ANTHO reçoit: Seth Jarvis, Igor Shesterkin'),
('2022-10-23',
 (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'),
 (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'),
 'CO reçoit: Nathan MacKinnon, Gabriel Landeskog | OLI reçoit: Robert Thomas, Clayton Keller, 1st round pick 2023'),
('2022-10-23',
 (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'),
 (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'),
 'SAM reçoit: Cam Talbot, Scott Perunovich, Matt Duchene, Roman Josi | OLI reçoit: Logan Thompson, Evan Bouchard, Patrick Laine, 1st round pick 2023, 3rd round pick 2023'),
('2022-10-23',
 (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'),
 (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'),
 'TALBOT reçoit: Sam Reinhart, 1st round pick 2023 | NADO reçoit: Vladimir Tarasenko'),
('2022-10-23',
 (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'),
 (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'),
 'TALBOT reçoit: Elias Petterson, Zach Werenski | SAM reçoit: Evgeni Malkin, Kris Letang'),
('2022-11-01',
 (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'),
 (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'),
 'OLI reçoit: Bowen Byram, Jake Sanderson, Timo Meier, Elias Lindholm, 2nd round pick 2023 | NADO reçoit: Sebastian Aho, Logan Thompson, 2nd round pick 2024'),
('2022-11-10',
 (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'),
 (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'),
 'SAM reçoit: Erik Karlsson, Alex Ovechkin | CO reçoit: Mikko Rantanen, Jakub Chykrun'),
('2022-11-15',
 (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'),
 (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'),
 'NADO reçoit: Alex Pietrangelo, Brent Burns | TALBOT reçoit: Owen Power, Nikolaj Elhers'),
('2022-11-17',
 (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'),
 (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'),
 'ANTHO reçoit: Jack Hughes, Jesper Bratt, Sergei Bobrovsky, 2nd round pick 2023 | CO reçoit: Auston Matthews, Andrei Vasilevskiy, Devon Toews'),
('2022-11-30',
 (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'),
 (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'),
 'OLI reçoit: Lucas Raymond, Taylor Hall, 2nd round pick 2024 | SAM reçoit: Zach Hyman, Rasmus Andersson'),
('2022-12-01',
 (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'),
 (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'),
 'NADO reçoit: Ryan Nugent-Hopkins, Blake Wheeler, Gustav Forsling | TALBOT reçoit: Sebastian Aho, Samuel Girard, Phil Kessel, 4th round pick 2023'),
('2022-12-01',
 (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'),
 (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'),
 'ANTHO reçoit: Vitek Vanecek, Nico Hischier, Patrick Kane | CO reçoit: Igor Shesterkin, Johnny Gaudreau, William Nylander'),
('2022-12-19',
 (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'),
 (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'),
 'NADO reçoit: Elias Petterson, Claude Giroux | TALBOT reçoit: Dylan Larkin, Noah Dobson, Victor Hedman'),
('2023-01-13',
 (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'),
 (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'),
 'CO reçoit: Leon Draisaitl | ANDREW reçoit: Josh Morrissey, Mark Stone, Andrei Vasilevskiy, 3rd round pick 2023'),
('2023-01-21',
 (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'),
 (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'),
 'ANTHO reçoit: Anton Lundell, Dawson Mercer | ANDREW reçoit: Patrick Kane, Chandler Stephenson, 3rd round pick 2023'),
('2023-01-22',
 (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'),
 (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'),
 'ANTHO reçoit: Connor Hellebuyk, Gustav Forsling, Jack Guentzel, Mark Giordano, 1st round pick 2024, 5th round pick 2023 | NADO reçoit: Jack Hughes, Pierre-Luc Dubois, Jack Campbell, Seth Jones'),
('2023-02-01',
 (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'),
 (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'),
 'ANTHO reçoit: Jack Eichel, Alex Newhook, John Gibson, 2nd round pick 2024 | CO reçoit: Aleksander Barkov, Brandon Montour'),
('2023-03-01',
 (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'),
 (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'),
 'OLI reçoit: Luke Hughes, Morgan Rielly, Matt Murray, 1nd round pick 2023 | ANDREW reçoit: Rasmus Dahlin, 3th round pick 2023'),
('2023-03-01',
 (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'),
 (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'),
 'OLI reçoit: Trevor Zegras, Johnny Gaudreau, Miro Heiskanen, Jamie Drysdale, 1st round pick 2024 | CO reçoit: Matthew Tkachuk, Brady Tkachuk, Jake Sanderson'),
('2023-03-01',
 (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'),
 (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'),
 'OLI reçoit: Mathew Barzal | SAM reçoit: Martin Jones, 4th round pick 2023, 5th round pick 2023, 6th round pick 2023'),
('2023-03-01',
 (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'),
 (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'),
 'NADO reçoit: Matthew Boldy, Jordan Kyrou, Drake Batherson, Matt Duchene, Tristan Jarry, Cam Talbot, Rasmus Andersson, 1st round pick 2024, 3rd round pick 2024, 6th round pick 2023 (VIA OLI) | SAM reçoit: Sidney Crosby, John Tavares, Mika Zibanejad, Claude Giroux, Brent Burns'),
('2023-03-03',
 (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'),
 (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'),
 'CO reçoit: Brayden Point, Kyle Connor | ANDREW reçoit: Auston Matthews, Aleksander Barkov'),
('2023-09-08',
 (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'),
 (SELECT id FROM equipes WHERE nom = 'Alex Lirette (TEMPORAIRE)'),
 'NADO reçoit: Philip Hronek, 3rd round pick 2023 | LIRETTE reçoit: Drew Doughty, Evander Kane');

-- Ballotage décembre 2022
INSERT INTO repechages (annee, type_id, equipe_id, joueur, rang) VALUES
(2022, (SELECT id FROM types_repechage WHERE nom = 'Ballotage'), (SELECT id FROM equipes WHERE nom = 'Les Enculés de Westmount'), 'Martin Necas', 1),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Ballotage'), (SELECT id FROM equipes WHERE nom = 'Les Chiennes de Granby'), 'Kirby Dach', 2),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Ballotage'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Ville Husso', 3),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Ballotage'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Brad Marchand', 4),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Ballotage'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Andre Burakovsky', 5),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Ballotage'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Vitek Vanecek', 6),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Ballotage'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Andrei Kuzmenko', 7);

-- Ballotage mars 2023
INSERT INTO repechages (annee, type_id, equipe_id, joueur, rang) VALUES
(2023, (SELECT id FROM types_repechage WHERE nom = 'Ballotage'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Linus Ullmark', 1),
(2023, (SELECT id FROM types_repechage WHERE nom = 'Ballotage'), (SELECT id FROM equipes WHERE nom = 'Les Enculés de Westmount'), 'Dylan Cozens', 2),
(2023, (SELECT id FROM types_repechage WHERE nom = 'Ballotage'), (SELECT id FROM equipes WHERE nom = 'Les Chiennes de Granby'), 'Martin Jones', 3),
(2023, (SELECT id FROM types_repechage WHERE nom = 'Ballotage'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Travis Konecny', 4),
(2023, (SELECT id FROM types_repechage WHERE nom = 'Ballotage'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Luke Hughes', 5),
(2023, (SELECT id FROM types_repechage WHERE nom = 'Ballotage'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Ilya Samsonov', 6),
(2023, (SELECT id FROM types_repechage WHERE nom = 'Ballotage'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Vince Dunn', 7);

-- Draft annuel 2022-2023 (choix 1 à 50)
INSERT INTO repechages (annee, type_id, equipe_id, joueur, rang) VALUES
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Connor McDavid', 1),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Leon Draisaitl', 2),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Auston Matthews', 3),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Cale Makar', 4),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Nathan Mackinnon', 5),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Krill Kaprizov', 6),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Igor Shesterkin', 7),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Mitchell Marner', 8),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Jonathan Huberdeau', 9),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Roman Josi', 10),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Nikita Kucherov', 11),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Andrei Vasilevskiy', 12),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Artemi Panarin', 13),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Jakob Markstrom', 14),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Victor Hedman', 15),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Adam Fox', 16),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Aleksander Barkov', 17),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Mikko Rantanen', 18),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Sebastian Aho', 19),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Frederik Andersen', 20),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Jack Eichel', 21),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Jack Hughes', 22),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Andrei Svechnikov', 23),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Matthew Tkachuk', 24),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Quinn Hughes', 25),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Johnny Gaudreau', 26),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Filip Forsberg', 27),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Jake Guentzel', 28),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Sidney Crosby', 29),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Kyle Connor', 30),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Jack Campbell', 31),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Jason Robertson', 32),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Moritz Seider', 33),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Thatcher Demko', 34),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Trevor Zegras', 35),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Miro Heiskanen', 36),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Aaron Ekblad', 37),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Juuse Saros', 38),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Jordan Kyrou', 39),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Alex Debrincat', 40),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Morgan Rielly', 41),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Anton Forsberg', 42),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Mika Zibanejad', 43),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Matt Murray', 44),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'William Nylander', 45),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Elias Petterson', 46),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Matt Duchene', 47),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Ilya Sorokin', 48),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Shea Theodore', 49),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Robert Thomas', 50);

-- Draft annuel 2022-2023 (choix 51 à 100)
INSERT INTO repechages (annee, type_id, equipe_id, joueur, rang) VALUES
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Kris Letang', 51),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Brady Tkachuk', 52),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Jordan Binnington', 53),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Devon Toews', 54),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'J.T. Miller', 55),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Evander Kane', 56),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Timo Meier', 57),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Brayden Point', 58),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Mark Scheifele', 59),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Matthew Barzal', 60),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Pavel Buchnevich', 61),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Josh Norris', 62),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'David Pastrnak', 63),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Thomas Chabot', 64),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Brent Burns', 65),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Gabriel Landeskog', 66),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Patrick Laine', 67),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'John Carlson', 68),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Kevin Fiala', 69),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Elias Lindholm', 70),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Nazem Kadri', 71),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Charlie Mcavoy', 72),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Sergei Bobrovsky', 73),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Zach Werenski', 74),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Rasmus Dahlin', 75),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Mackenzie Weegar', 76),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Jesper Bratt', 77),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Tim Stützle', 78),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Evgeni Malkin', 79),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Tage Thompson', 80),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Matthew Boldy', 81),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Nick Suzuki', 82),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Troy Terry', 83),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Noah Dobson', 84),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Connor Hellebuyck', 85),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Alexander Georgiev', 86),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Seth Jones', 87),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Evan Bouchard', 88),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Roope Hintz', 89),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Mason Mctavish', 90),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Jake Oettinger', 91),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Patrick Kane', 92),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Sam Bennett', 93),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Matty Beniers', 94),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Evgeny Kuznetsov', 95),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Andrew Mangiapane', 96),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Mikhail Sergachev', 97),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Owen Power', 98),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Sam Reinhart', 99),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Dougie Hamilton', 100);

-- Draft annuel 2022-2023 (choix 101 à 150)
INSERT INTO repechages (annee, type_id, equipe_id, joueur, rang) VALUES
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Brandon Montour', 101),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Boone Jenner', 102),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Brandon Hagel', 103),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Ryan Nugent-Hopkins', 104),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Brayden Schenn', 105),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Claude Giroux', 106),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Jamie Drysdale', 107),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Alex Tuch', 108),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Vladimir Tarasenko', 109),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Tyler Bertuzzi', 110),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Dylan Larkin', 111),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Pierre-Luc Dubois', 112),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Jakub Chychrun', 113),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Logan Thompson', 114),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Tyler Toffoli', 115),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Brandon Saad', 116),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Darnell Nurse', 117),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Alex Killorn', 118),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Sean Couturier', 119),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Jonathan Marchessault', 120),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Brady Skjei', 121),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Ryan Hartman', 122),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Drew Doughty', 123),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Dylan Strome', 124),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Jared Spurgeon', 125),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Ryan Pulock', 126),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Anthony Beauvillier', 127),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Nikolaj Ehlers', 128),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Ryan O’Reilly', 129),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Tyson Barrie', 130),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Brendan Gallagher', 131),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Tomas Hertl', 132),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Ivan Barbashev', 133),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Alex Pietrangelo', 134),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Jared McCann', 135),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Samuel Girard', 136),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Blake Wheeler', 137),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Joel Eriksson Ek', 138),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Tyler Seguin', 139),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Damon Severson', 140),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Matt Dumba', 141),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Jake Sanderson', 142),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Sean Monahan', 143),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Oliver Kylington', 144),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Alexis Lafrenière', 145),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Nico Hischier', 146),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Ryan Graves', 147),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Phil Kessel', 148),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Mark Stone', 149),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Brandon Carlo', 150);

-- Draft annuel 2022-2023 (choix 151 à 182)
INSERT INTO repechages (annee, type_id, equipe_id, joueur, rang) VALUES
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Josh Morrissey', 151),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Dylan Cozens', 152),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Cam Talbot', 153),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Chandler Stephenson', 154),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Dawson Mercer', 155),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Bowen Byram', 156),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Scott Perunovich', 157),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Anton Lundell', 158),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Lucas Raymond', 159),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Taylor Hall', 160),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Seth Jarvis', 161),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Gustav Forsling', 162),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Alex Newhook', 163),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'John Gibson', 164),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Samuel Girard', 165),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Clayton Keller', 166),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Erik Karlsson', 167),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Jack Guentzel', 168),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Mark Giordano', 169),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Mikael Backlund', 170),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Samuel Montembeault', 171),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Les Ptit-Pains Fourrés de Limoilou'), 'Kaapo Kahkonen', 172),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Consanguins de Laterrière'), 'Jack Campbell', 173),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Tristan Jarry', 174),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Rasmus Andersson', 175),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'Philipp Grubauer', 176),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Cam Talbot', 177),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Canadiens Français de la Rivière aux Graines'), 'Drake Batherson', 178),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Enculés de Westmount'), 'John Tavares', 179),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Chiennes de Granby'), 'Claude Giroux', 180),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Dream Team de Saint-Pie-X'), 'Brent Burns', 181),
(2022, (SELECT id FROM types_repechage WHERE nom = 'Draft annuel'), (SELECT id FROM equipes WHERE nom = 'Vidanges de Rimouski'), 'Phillip Danault', 182);